name: auth_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  axons_totp:
    git: 
      url: https://github.com/AxonDesigns/axons_totp.git
  numberpicker: ^2.1.2
  go_router: ^14.6.2
  path_provider: ^2.1.5
  async_widget_builder:
    git: 
      url: https://github.com/AxonDesigns/async_widget_builder.git
  modal_bottom_sheet: ^3.0.0
  hive_ce: ^2.8.0+2
  hive_ce_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_ce_generator: ^1.8.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  fonts:
    - family: JetbrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Variable.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-VariableItalic.ttf
          style: italic